network: "SATRN"
charset: "./resources/charset.txt"
resize_hw:
  height: 32
  width: 100
use_rgb: False
label_maxlen: 25
seed: 42
model_dir: "../saved_models/satrn_aida"

hidden_size: 512
filter_size: 2048
enc_layers: 12
dec_layers: 6
num_heads: 8
dropout_rate: 0.9 
rot_stddev: 0.6

train:
  dataset_paths:
      - "/home/cylee/data/aida/tfrecords/train/aida-words-0.tfrecord"     # 8K  aida
  dataset_portions:
    - 1.0
  lowercase: False
  alphanumeric: False
  batch_size: 32
  num_threads: 8
  tune_from: ""
  max_num_steps: 250001
  verbose: False
  save_steps: 5000
  summary_steps: 1000
  optimizer:
    optimizer: 'Adam'
    learning_rate: 0.0003
    beta2: 0.999
    use_clr: True
    clr_step: 250000
    grad_clip_norm: 2.

valid:
  dataset_paths:
      - "/home/cylee/data/aida/tfrecords/test/aida-words-9.tfrecord"     # 2K  aida
  lowercase: True
  alphanumeric: True
  batch_size: 32
  steps: 1000

eval:
  dataset_paths: 
      - "/home/cylee/data/aida/tfrecords/test/aida-words-*.tfrecord"     # 2K  aida
  lowercase: True
  alphanumeric: True
  model_path: "../saved_models/satrn/model"
  batch_size: 32
  verbose: False  

